site_name: My Docs
site_url: https://paladinaura.com
plugins:
   - search
   - awesome-nav
theme:
  name: material
nav:
  - Home: index.md
  - About: about.md
  - Health:
      - Chart: health/grandtable.md
      - Vitamins: health/Vitamins/*